CREATE TABLE IF NOT EXISTS users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(256)  NOT NULL,
    email      VARCHAR(512)  NOT NULL,
    CONSTRAINT pk_user       PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(256),
    description  VARCHAR(256),
    is_available BOOLEAN,
    owner_id     BIGINT,
    CONSTRAINT   pk_item      PRIMARY KEY (id),
    CONSTRAINT   fk_item_user FOREIGN KEY (owner_id) references users (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED ALWAYS AS IDENTITY,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date   TIMESTAMP WITHOUT TIME ZONE,
    item_id    BIGINT,
    booker_id  BIGINT,
    status     VARCHAR(256),
    CONSTRAINT pk_booking      PRIMARY KEY (id),
    CONSTRAINT fk_booking_item FOREIGN KEY (item_id)   references items (id),
    CONSTRAINT fk_booking_user FOREIGN KEY (booker_id) references users (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id          BIGINT GENERATED ALWAYS AS IDENTITY,
    text        TEXT(512)                   NOT NULL,
    item_id     BIGINT                      NOT NULL,
    author_id   BIGINT                      NOT NULL,
    created     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT  pk_comments     PRIMARY KEY (id),
    CONSTRAINT  fk_comment_item FOREIGN KEY (item_id)   references items (id),
    CONSTRAINT  fk_comment_user FOREIGN KEY (author_id) references users (id)
);